application: wide-exchanger-382
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'toodo.settings'

handlers:
- url: /static
  static_dir: static